server:
    port: 9003
spring:
    application:
        name: dispatcher-service
    cloud:
        function:
            definition: pack|label
        stream:
            bindings:
                packlabel-in-0:
                    destination: order-accepted
                    group: ${spring.application.name}
                packlabel-out-0:
                    destination: order-dispatched
        config:
            enabled: false
            fail-fast: false # In production, set to true
            retry:
                max-attempts: 5
                initial-interval: 1000
                max-interval: 2000
                multiplier: 1.1
            request-connect-timeout: 5000
            request-read-timeout: 5000
            uri: http://localhost:8888
    config:
        import: ''

    rabbitmq:
        host: localhost
        port: 5672
        username: user
        password: password
        connection-timeout: 5s

polar:
    greeting: 'Welcome to the local ${spring.application.name}!'


management:
    endpoints:
        web:
            exposure:
                include:
                    - refresh
                    - health
                    - metrics
                    - prometheus

    endpoint:
        health:
            show-components: always
            show-details: always
            probes:
                enabled: true
            group:
                readiness:
                    include:
                        - readinessState
                        - rabbit
                liveness:
                    include:
                        - livenessState
    metrics:
        tags:
            application: ${spring.application.name}

logging:
    pattern:
        level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"